shared_settings: &shared_settings
  project_name: ""
  jtj_api_url: "http://jtj-staging.watermark.org/api"

  
development: &non_production_settings
  <<: *shared_settings
  domain: localhost:3000

test:
  <<: *non_production_settings
  <<: *shared_settings

staging:
  <<: *non_production_settings
  <<: *shared_settings

production:
  disqus_short_name: goforclass
  <<: *shared_settings